import React from 'react';
import { AbsoluteFill, spring, useCurrentFrame, useVideoConfig } from 'remotion';
import { tokens } from '../tokens';
import type { ZoomPlan, ZoomMoment, SmartZoomEasing } from '../types';

type Props = {
  plan: ZoomPlan | null | undefined;
  children: React.ReactNode;
};

// Where in the frame we want the face to land while zoomed in.
// Upper-third horizontal-center is the standard talking-head composition rule.
const FACE_TARGET_X_RATIO = 0.5;
const FACE_TARGET_Y_RATIO = 0.33;

function findActiveMoment(t: number, moments: ZoomMoment[]): ZoomMoment | null {
  for (const m of moments) {
    if (t >= m.startSec && t <= m.endSec) return m;
  }
  return null;
}

function resolveEasing(moment: ZoomMoment): SmartZoomEasing {
  return moment.easing ?? 'dolly_in';
}

/**
 * Computes the current zoom scale by easing into the target zoom at the start
 * of the moment, holding, and easing back out at the end.
 *
 * Phase 10 Round A Tier 2 — A6: the easing curve (spring physics + ramp
 * durations) is per-moment. Phase 6 picks based on audio energy.
 */
function computeScale(
  frame: number,
  fps: number,
  moment: ZoomMoment,
): number {
  const startFrame = Math.round(moment.startSec * fps);
  const endFrame = Math.round(moment.endSec * fps);
  const localFrame = frame - startFrame;
  const totalFrames = endFrame - startFrame;
  const target = moment.zoomLevel;

  const curve = tokens.smartZoomCurves[resolveEasing(moment)];
  const rampIn = curve.rampInFrames;
  const rampOut = curve.rampOutFrames;

  if (totalFrames <= rampIn + rampOut) {
    // Moment too short for a full ramp — just hold at target after a quick ease.
    const progress = spring({
      frame: localFrame,
      fps,
      config: curve.spring,
    });
    return 1 + (target - 1) * progress;
  }

  if (localFrame < rampIn) {
    // Easing in
    const progress = spring({
      frame: localFrame,
      fps,
      config: curve.spring,
    });
    return 1 + (target - 1) * progress;
  }

  if (localFrame > totalFrames - rampOut) {
    // Easing out
    const exitFrame = localFrame - (totalFrames - rampOut);
    const progress = spring({
      frame: exitFrame,
      fps,
      config: curve.spring,
    });
    return target + (1 - target) * progress;
  }

  // Holding
  return target;
}

/**
 * SmartZoom — wraps the lecturer video and applies a Ken Burns-style zoom
 * around the lecturer's face during emphasized moments.
 *
 * The zoom plan is generated by Claude Code (Phase 5/6) from face_map.json +
 * audio_energy.json. This component is stateless and just renders the transform
 * for the current frame.
 *
 * Wraps `children` in a transformed container — children should be a single
 * full-bleed video layer (e.g. <VideoTrack />). Captions / logo / lower-third
 * must NOT be wrapped — they should sit at the same level as <SmartZoom>.
 */
export const SmartZoom: React.FC<Props> = ({ plan, children }) => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();

  if (!plan || plan.moments.length === 0) {
    return <>{children}</>;
  }

  const t = frame / fps;
  const moment = findActiveMoment(t, plan.moments);

  if (!moment) {
    return <>{children}</>;
  }

  const scale = computeScale(frame, fps, moment);

  // Where the face is in the original (pre-scale) frame, in pixels
  const cx = (moment.centerX ?? 0.5) * width;
  const cy = (moment.centerY ?? 0.4) * height;

  // Where we want the face to end up on screen
  const targetX = width * FACE_TARGET_X_RATIO;
  const targetY = height * FACE_TARGET_Y_RATIO;

  // Translation needed so that scaled face lands on target
  let tx = targetX - cx * scale;
  let ty = targetY - cy * scale;

  // Clamp so the video edges never reveal black areas
  const minTx = width * (1 - scale);
  const minTy = height * (1 - scale);
  tx = Math.min(0, Math.max(minTx, tx));
  ty = Math.min(0, Math.max(minTy, ty));

  return (
    <AbsoluteFill
      style={{
        transformOrigin: '0 0',
        transform: `translate(${tx}px, ${ty}px) scale(${scale})`,
      }}
    >
      {children}
    </AbsoluteFill>
  );
};
