export type WordTiming = {
  word: string;
  start: number;
  end: number;
};

export type CaptionSegment = {
  id?: number;
  start: number;
  end: number;
  text: string;
  words: WordTiming[];
};

export type CaptionsData = {
  language: string;
  totalDuration: number;
  segmentCount: number;
  segments: CaptionSegment[];
};

/**
 * Phase 10 Round A Tier 2 — A6: per-moment easing curve for Smart Zoom.
 * Phase 6 picks based on audio energy: high → crash_zoom, medium →
 * dolly_in, low → smooth_glide. Defaults to 'dolly_in' when absent.
 */
export type SmartZoomEasing = 'smooth_glide' | 'dolly_in' | 'crash_zoom';

export type ZoomMoment = {
  /** Start time in seconds, relative to the lecture timeline */
  startSec: number;
  /** End time in seconds */
  endSec: number;
  /** Target zoom level (e.g. 1.4 for 1.4x) */
  zoomLevel: number;
  /** Face center X (0-1 normalized to comp width). Defaults to 0.5 if absent. */
  centerX?: number;
  /** Face center Y (0-1 normalized to comp height). Defaults to 0.4 if absent. */
  centerY?: number;
  /** Optional human-readable reason — appears in dev logs / Studio inspector */
  reason?: string;
  /**
   * Phase 10 Round A Tier 2 — optional named easing curve for this moment.
   * Defaults to 'dolly_in' when absent (matches legacy smoothness).
   */
  easing?: SmartZoomEasing;
};

export type ZoomPlan = {
  /** Source identifier (video filename or hash) — for sanity checks */
  source?: string;
  /** Spring config name from tokens.springs (default 'smooth') */
  spring?: 'enter' | 'exit' | 'bounce' | 'smooth';
  moments: ZoomMoment[];
};

// ─── Animation Plan (Phase 6) ─────────────────────────────────────────────
// The plan generated by Claude Code from content_analysis.json + face_map +
// energy. Phase 7 components consume this to render scenes / overlays.

export type SceneType = 'process_stepper' | 'process_timeline' | 'comparison_two_paths' | 'big_metaphor';

// ─── Scene Entrance (Phase 10 Round A — animation variety) ──────────────
/**
 * Wrapper-level entrance animation for a full-screen scene. Applied to the
 * whole scene container — the scene's internal element animations still
 * run independently after the wrapper settles.
 *
 * - `fade`           : simple opacity fade (default, current behavior)
 * - `scale_bounce`   : scale 0.85 → 1.0 with spring overshoot + opacity
 * - `blur_reveal`    : blur 20px → 0px + opacity
 * - `stagger_cascade`: very quick opacity so child stagger is the main show
 */
export type SceneEntrance = 'fade' | 'scale_bounce' | 'blur_reveal' | 'stagger_cascade';

/**
 * Wrapper-level exit animation (Tier 2). Mirrors entrance in intent —
 * plan-driven variety on the way out.
 *
 * - `fade`      : opacity 1 → 0 (default)
 * - `scale_out` : opacity + scale 1.0 → 1.08 (punches out)
 * - `slide_down`: opacity + translateY 0 → 80px (drifts down)
 */
export type SceneExit = 'fade' | 'scale_out' | 'slide_down';

export type StepCardElement = {
  type: 'step_card';
  step: number;
  label: string;
  icon?: string;
  status?: 'current' | 'next' | 'future' | 'highlighted';
  status_badge?: string;
  stagger_delay_frames?: number;
};

export type ConnectorArrowElement = {
  type: 'connector_arrow';
  between?: number[];
  color?: string;
  delay_frames?: number;
};

export type TimelineItem = {
  label: string;
  status: 'done' | 'next' | 'future';
  status_text?: string;
  color?: string;
};

export type TimelineElement = {
  type: 'timeline_horizontal';
  items: TimelineItem[];
  stagger_per_item_frames?: number;
  show_arrows_between?: boolean;
};

export type FooterCaptionElement = {
  type: 'footer_caption';
  text: string;
  size?: number;
  font?: string;
  weight?: number;
  color?: string;
  delay_frames?: number;
};

export type TwoPathsSide = {
  label: string;
  icon?: 'check' | 'x';
  icon_color?: string;
  icon_opacity?: number;
  steps: string[];
  step_color?: string;
  highlight?: string;
  highlight_color?: string;
  highlight_opacity?: number;
};

export type ComparisonTwoPathsElement = {
  type: 'comparison_two_paths';
  left: TwoPathsSide;
  right: TwoPathsSide;
  stagger_delay_frames?: number;
};

export type BigMetaphorElement = {
  type: 'big_metaphor';
  headline: string;
  headline_size?: number;
  headline_color?: string;
  headline_font?: string;
  headline_weight?: number;
  subline?: string;
  subline_size?: number;
  subline_color?: string;
  subline_font?: string;
  subline_weight?: number;
  subline_delay_frames?: number;
  footer_label?: string;
  footer_size?: number;
  footer_color?: string;
  footer_opacity?: number;
  footer_delay_frames?: number;
};

// ─── New scene types (Phase 7 iteration 2) ────────────────────────────────

export type DefinitionElement = {
  type: 'definition';
  /** The term being defined (big accent text) */
  term: string;
  /** Optional Arabic translation / pronunciation under the term */
  term_sub?: string;
  /** The definition body (3-8 words, white) */
  definition: string;
  /** Optional example under the definition */
  example?: string;
  /** Optional icon character (emoji or single letter) */
  icon?: string;
};

export type EquationTerm = {
  /** The token text (variable, number, or operator) */
  text: string;
  /** Optional label underneath (e.g. "الأصول" under "A") */
  label?: string;
  /** Is this the final result? (styled differently) */
  is_result?: boolean;
};

export type EquationElement = {
  type: 'equation';
  /** Array of equation tokens, rendered left-to-right with stagger */
  terms: EquationTerm[];
  /** Optional title above the equation */
  title?: string;
  /** Optional footer label below */
  footer?: string;
};

export type CounterElement = {
  type: 'counter';
  /** The final value the counter stops at */
  value: number;
  /** Optional suffix (e.g. "+", "٪") */
  suffix?: string;
  /** Optional prefix (e.g. "$") */
  prefix?: string;
  /** Label above the number (e.g. "عدد المتدربين") */
  label_top?: string;
  /** Label below the number (e.g. "محاسب اتدرّب معانا") */
  label_bottom?: string;
  /** Count-up duration in frames (default 45 = 1.5s) */
  duration_frames?: number;
};

export type SceneElement =
  | StepCardElement
  | ConnectorArrowElement
  | TimelineElement
  | FooterCaptionElement
  | ComparisonTwoPathsElement
  | BigMetaphorElement
  | DefinitionElement
  | EquationElement
  | CounterElement;

export type Scene = {
  id: string;
  type: 'full_screen_scene';
  scene_type: string;
  start_sec: number;
  end_sec: number;
  duration_sec?: number;
  background?: string;
  title?: string;
  subtitle?: string;
  title_size?: number;
  title_font?: string;
  title_weight?: number;
  elements: SceneElement[];
  transition_in?: { type: string; frames: number };
  transition_out?: { type: string; frames: number };
  /**
   * Phase 10 Round A — wrapper-level entrance variety. Defaults to 'fade'
   * (matches existing behavior) when absent. Phase 6 picks per scene based
   * on scene_type.
   */
  entrance?: SceneEntrance;
  /** Phase 10 Round A Tier 2 — wrapper-level exit variety. Defaults 'fade'. */
  exit?: SceneExit;
};

export type OverlayType = 'keyword_highlight' | 'stamp';

export type OverlayItem = {
  id: string;
  type: 'overlay';
  overlay_type: OverlayType;
  start_sec: number;
  end_sec: number;
  /** Single big keyword (the term being highlighted) */
  keyword?: string;
  /** When the overlay shows a 2-line layout: primary + secondary */
  primary_text?: string;
  primary_color?: string;
  primary_size?: number;
  primary_weight?: number;
  secondary_text?: string;
  secondary_color?: string;
  secondary_size?: number;
  secondary_weight?: number;
  text?: string;
  text_color?: string;
  font?: string;
  weight?: number;
  size?: number;
  position?: 'top-center' | 'top-right' | 'top-left' | 'center';
  y_px?: number;
  background?: string;
  background_padding?: string;
  background_radius?: number;
  badge?: string;
  badge_color?: string;
  stamp_style?: {
    border?: string;
    border_radius?: number;
    padding?: string;
    rotation_deg?: number;
  };
};

// ─── WordCaption Emphasis (Phase 10 Round A — variants) ────────────────
/**
 * Emphasis variant for the currently-active caption word during an
 * emphasis beat. Replaces the color-change approach (would have broken
 * the single-accent rule) with intensity variation on the same gold.
 *
 * - `normal`: scale 1.06 + base shadow — everyday active word
 * - `pop`   : scale 1.16 + letter-spacing kick — medium emphasis
 * - `glow`  : scale 1.22 + big accent shadow pulse — high emphasis (top 20%)
 */
export type EmphasisIntensity = 'normal' | 'pop' | 'glow';

export type EmphasisBeat = {
  /** Global seconds — the peak moment of the beat */
  time: number;
  /** Variant to apply to the currently-active word at `time` */
  intensity: EmphasisIntensity;
};

// ─── Micro-events (Tier 2 retention rhythm) ──────────────────────────────
export type MicroEventType =
  | 'mini_zoom'
  | 'word_pop'
  | 'caption_underline'
  | 'accent_flash'
  | 'corner_sweep'
  | 'border_pulse';

export type MiniZoomMicroEvent = {
  id: string;
  type: 'mini_zoom';
  start_sec: number;
  end_sec: number;
  zoom_level: number;
  center_x: number;
  center_y: number;
  intensity?: string;
  anchor_subtitle_id?: number;
  anchor_text?: string;
  source?: string;
};

export type WordPopMicroEvent = {
  id: string;
  type: 'word_pop';
  start_sec: number;
  end_sec: number;
  word: string;
  anchor_subtitle_id?: number;
  /**
   * Phase 10 Round A — intensity picks the WordCaption variant for the
   * active word. Accepts the new enum or the legacy freeform strings
   * ('low'|'medium'|'high') which get mapped at the caption layer.
   */
  intensity?: EmphasisIntensity | string;
  source?: string;
};

export type CaptionUnderlineMicroEvent = {
  id: string;
  type: 'caption_underline';
  start_sec: number;
  end_sec: number;
  anchor_subtitle_id?: number;
  intensity?: string;
  source?: string;
};

export type AccentFlashMicroEvent = {
  id: string;
  type: 'accent_flash';
  start_sec: number;
  end_sec: number;
  side: 'left' | 'right';
  anchor_subtitle_id?: number;
  intensity?: string;
  source?: string;
};

// ─── Phase 10 Round A Tier 2 — A7: expanded micro events ──────────────

export type CornerSweepMicroEvent = {
  id: string;
  type: 'corner_sweep';
  start_sec: number;
  end_sec: number;
  /** Which corner the sweep line starts from. Default 'top_right' (RTL). */
  corner?: 'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';
  anchor_subtitle_id?: number;
  intensity?: string;
  source?: string;
};

export type BorderPulseMicroEvent = {
  id: string;
  type: 'border_pulse';
  start_sec: number;
  end_sec: number;
  anchor_subtitle_id?: number;
  intensity?: string;
  source?: string;
};

export type MicroEvent =
  | MiniZoomMicroEvent
  | WordPopMicroEvent
  | CaptionUnderlineMicroEvent
  | AccentFlashMicroEvent
  | CornerSweepMicroEvent
  | BorderPulseMicroEvent;

// ─── Chapter Divider ─────────────────────────────────────────────────────
export type ChapterDivider = {
  id: string;
  type: 'chapter_divider';
  start_sec: number;
  end_sec: number;
  /** Section title (big) */
  title: string;
  /** Optional kicker text above the title (e.g. "القسم 2") */
  kicker?: string;
  /** Optional subtitle below the title */
  subtitle?: string;
  /** Background: default gradient if omitted */
  background?: string;
};

export type CaptionStyle =
  | 'hormozi'
  | 'pop'
  | 'karaoke'
  | 'box'
  | 'typewriter'
  | 'classic';

/**
 * Per-time-window caption style override. If any ranges are defined, a
 * caption segment falling inside one uses that range's style; otherwise it
 * falls back to the plan's top-level `caption_style` (default 'hormozi').
 * Used by Phase 6 to vary styles across a single reel for retention.
 */
export type CaptionStyleRange = {
  start_sec: number;
  end_sec: number;
  style: CaptionStyle;
  /** Optional reason — appears in the Phase 6 plan for human review. */
  reason?: string;
};

export type AnimationPlan = {
  schema_version?: number;
  /** Pipeline phase that produced the JSON (5 = content_analysis, 6 = animation_plan) */
  phase?: number;
  /** ISO date string (YYYY-MM-DD) when the plan was generated */
  generated_at?: string;
  /** Free-text identifier of the generator (e.g. "Claude Code (Claude Opus 4.7)") */
  generated_by?: string;
  source_video_basename?: string;
  /** Source-video metadata snapshot — captured at plan generation time */
  video?: {
    duration_sec: number;
    duration_str?: string;
    fps?: number;
    width?: number;
    height?: number;
    language?: string;
    dialect?: string;
    segment_count?: number;
  };
  /** Absolute paths to the pipeline artifacts the plan was built from */
  source?: {
    video?: string;
    video_scaled?: string;
    captions?: string;
    face_map?: string;
    energy?: string;
    metadata?: string;
  };
  /** Which caption renderer to use — default 'hormozi' */
  caption_style?: CaptionStyle;
  /** Optional per-time-window style overrides (Phase 6 auto-assigns these) */
  caption_style_ranges?: CaptionStyleRange[];
  smart_zoom_plan?: ZoomPlan;
  scenes?: Scene[];
  overlays?: OverlayItem[];
  micro_events?: MicroEvent[];
  chapter_dividers?: ChapterDivider[];
};

export type ReelProps = {
  videoSrc: string;
  captions: CaptionsData;
  lecturer: string;
  workshop: string;
  /** Optional Smart Zoom plan — if absent, video plays at 1.0x with no transform */
  zoomPlan?: ZoomPlan | null;
  /** Optional full animation plan (Phase 6 output) — scenes + overlays + smart zooms */
  animationPlan?: AnimationPlan | null;
  durationInFrames?: number;
};
