export type WordTiming = {
  word: string;
  start: number;
  end: number;
};

export type CaptionSegment = {
  id?: number;
  start: number;
  end: number;
  text: string;
  words: WordTiming[];
};

export type CaptionsData = {
  language: string;
  totalDuration: number;
  segmentCount: number;
  segments: CaptionSegment[];
};

export type ZoomMoment = {
  /** Start time in seconds, relative to the lecture timeline */
  startSec: number;
  /** End time in seconds */
  endSec: number;
  /** Target zoom level (e.g. 1.4 for 1.4x) */
  zoomLevel: number;
  /** Face center X (0-1 normalized to comp width). Defaults to 0.5 if absent. */
  centerX?: number;
  /** Face center Y (0-1 normalized to comp height). Defaults to 0.4 if absent. */
  centerY?: number;
  /** Optional human-readable reason — appears in dev logs / Studio inspector */
  reason?: string;
};

export type ZoomPlan = {
  /** Source identifier (video filename or hash) — for sanity checks */
  source?: string;
  /** Spring config name from tokens.springs (default 'smooth') */
  spring?: 'enter' | 'exit' | 'bounce' | 'smooth';
  moments: ZoomMoment[];
};

// ─── Animation Plan (Phase 6) ─────────────────────────────────────────────
// The plan generated by Claude Code from content_analysis.json + face_map +
// energy. Phase 7 components consume this to render scenes / overlays.

export type SceneType = 'process_stepper' | 'process_timeline' | 'comparison_two_paths' | 'big_metaphor';

export type StepCardElement = {
  type: 'step_card';
  step: number;
  label: string;
  icon?: string;
  status?: 'current' | 'next' | 'future';
  status_badge?: string;
  stagger_delay_frames?: number;
};

export type ConnectorArrowElement = {
  type: 'connector_arrow';
  between?: number[];
  color?: string;
  delay_frames?: number;
};

export type TimelineItem = {
  label: string;
  status: 'done' | 'next' | 'future';
  status_text?: string;
  color?: string;
};

export type TimelineElement = {
  type: 'timeline_horizontal';
  items: TimelineItem[];
  stagger_per_item_frames?: number;
  show_arrows_between?: boolean;
};

export type FooterCaptionElement = {
  type: 'footer_caption';
  text: string;
  size?: number;
  font?: string;
  weight?: number;
  color?: string;
  delay_frames?: number;
};

export type TwoPathsSide = {
  label: string;
  icon?: 'check' | 'x';
  icon_color?: string;
  icon_opacity?: number;
  steps: string[];
  step_color?: string;
  highlight?: string;
  highlight_color?: string;
  highlight_opacity?: number;
};

export type ComparisonTwoPathsElement = {
  type: 'comparison_two_paths';
  left: TwoPathsSide;
  right: TwoPathsSide;
  stagger_delay_frames?: number;
};

export type BigMetaphorElement = {
  type: 'big_metaphor';
  headline: string;
  headline_size?: number;
  headline_color?: string;
  headline_font?: string;
  headline_weight?: number;
  subline?: string;
  subline_size?: number;
  subline_color?: string;
  subline_font?: string;
  subline_weight?: number;
  subline_delay_frames?: number;
  footer_label?: string;
  footer_size?: number;
  footer_color?: string;
  footer_opacity?: number;
  footer_delay_frames?: number;
};

export type SceneElement =
  | StepCardElement
  | ConnectorArrowElement
  | TimelineElement
  | FooterCaptionElement
  | ComparisonTwoPathsElement
  | BigMetaphorElement;

export type Scene = {
  id: string;
  type: 'full_screen_scene';
  scene_type: string;
  start_sec: number;
  end_sec: number;
  duration_sec?: number;
  background?: string;
  title?: string;
  subtitle?: string;
  title_size?: number;
  title_font?: string;
  title_weight?: number;
  elements: SceneElement[];
  transition_in?: { type: string; frames: number };
  transition_out?: { type: string; frames: number };
};

export type OverlayType = 'keyword_highlight' | 'stamp';

export type OverlayItem = {
  id: string;
  type: 'overlay';
  overlay_type: OverlayType;
  start_sec: number;
  end_sec: number;
  /** Single big keyword (the term being highlighted) */
  keyword?: string;
  /** When the overlay shows a 2-line layout: primary + secondary */
  primary_text?: string;
  primary_color?: string;
  primary_size?: number;
  primary_weight?: number;
  secondary_text?: string;
  secondary_color?: string;
  secondary_size?: number;
  secondary_weight?: number;
  text?: string;
  text_color?: string;
  font?: string;
  weight?: number;
  size?: number;
  position?: 'top-center' | 'top-right' | 'top-left' | 'center';
  y_px?: number;
  background?: string;
  background_padding?: string;
  background_radius?: number;
  badge?: string;
  badge_color?: string;
  stamp_style?: {
    border?: string;
    border_radius?: number;
    padding?: string;
    rotation_deg?: number;
  };
};

// ─── Micro-events (Tier 2 retention rhythm) ──────────────────────────────
export type MicroEventType = 'mini_zoom' | 'word_pop' | 'caption_underline' | 'accent_flash';

export type MiniZoomMicroEvent = {
  id: string;
  type: 'mini_zoom';
  start_sec: number;
  end_sec: number;
  zoom_level: number;
  center_x: number;
  center_y: number;
  intensity?: string;
  anchor_subtitle_id?: number;
  anchor_text?: string;
  source?: string;
};

export type WordPopMicroEvent = {
  id: string;
  type: 'word_pop';
  start_sec: number;
  end_sec: number;
  word: string;
  anchor_subtitle_id?: number;
  intensity?: string;
  source?: string;
};

export type CaptionUnderlineMicroEvent = {
  id: string;
  type: 'caption_underline';
  start_sec: number;
  end_sec: number;
  anchor_subtitle_id?: number;
  intensity?: string;
  source?: string;
};

export type AccentFlashMicroEvent = {
  id: string;
  type: 'accent_flash';
  start_sec: number;
  end_sec: number;
  side: 'left' | 'right';
  anchor_subtitle_id?: number;
  intensity?: string;
  source?: string;
};

export type MicroEvent =
  | MiniZoomMicroEvent
  | WordPopMicroEvent
  | CaptionUnderlineMicroEvent
  | AccentFlashMicroEvent;

export type AnimationPlan = {
  schema_version?: number;
  source_video_basename?: string;
  smart_zoom_plan?: ZoomPlan;
  scenes?: Scene[];
  overlays?: OverlayItem[];
  micro_events?: MicroEvent[];
};

export type ReelProps = {
  videoSrc: string;
  captions: CaptionsData;
  lecturer: string;
  workshop: string;
  /** Optional Smart Zoom plan — if absent, video plays at 1.0x with no transform */
  zoomPlan?: ZoomPlan | null;
  /** Optional full animation plan (Phase 6 output) — scenes + overlays + smart zooms */
  animationPlan?: AnimationPlan | null;
  durationInFrames?: number;
};
